# Generated by Django 3.2.7 on 2021-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.IntegerField(blank=True, default=99999)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10)),
                ('photo', models.ImageField(blank=True, upload_to='restaurantImages')),
                ('price', models.CharField(blank=True, max_length=200)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
            ],
        ),
    ]
